- static/login.css
- templates/login.html
I created the basic HTML form and CSS to get user login credentials.
> Creating the login form.

- static/homeheader.css
- templates/homeheader.html
I created a simple header to set up the sign-out button. Includes simple CSS file.
> Simple header with sign out button, and simple css.

- static/userPlaylistpage.css
- templates/userPlaylistpage.html
A basic view of the User's Homepage which shows all their playlist information is created.
> User Home+Playlist Page

- static/homeheader.css
- templates/homeheader.html
Linked the Sign-Out button of Header (homeheader.html) to landingpage.html of the WebApp.
After Clicking on the Sign-out button. It goes to the Landing Page of the WebApp
> Linking the Sign out button to the Landing Page of the WebApp

- static/landfooter.css
- static/landheader.css
- static/landingpage.css
- templates/landfooter.html
- templates/landheader.html
- templates/landingpage.html
Created the header for the landing page (this is the page you land on when you would click Verge from google). Used bootstrap to make things easier and a lot more seamless. I plan to update older HTML pages with bootstrap as well. 
The Playlist, Passcode, Collaboration, etc buttons highlight when you hover over them.
The Sign In button also highlights when you hover over it.
> Landing Page Header

- templates/login.html
- templates/signup.html
I added the header and footer to the login & signup pages.
> Adding the header and footer to the login and signup HTML files.

- main.py
- templates/PlaylistMore.html
- templates/createPlaylistPage.html
- templates/login.html
- templates/playlistpage.html
- templates/signup.html
- templates/userPlaylistpage.html
Making sure the headers and footers work
login page:
Sign in page:
userPlaylistpage
createPlaylistPage
> Adding the headers and footers to pages

- Milestone.md
"The queued song will refresh and now show as an item, implement a queue (songs will not be playing from MVP)."
This was recommended by Professor Zamansky - to indicate that we will not be playing music by MVP.
> Updated MVP info

- main.py
- templates/playlistpage.html
Created Playlist:
and it goes to the individual playlistpage
> Created playlist now goes to the Playlist Page

- read-me.md
- requirements.txt
created requirements.txt and fixed formatting issue in read-me
> requirements

- .cache
- main.py
- templates/homeheader.html
- templates/playlistpage.html
The remove button is shown next to each song in the queue and when it is clicked, the song should be removed from the queue and database.
> Remove button and function added 

- databasefunctions.py
- main.py
- testingplaylistfunctions.py
Created a  unit test the RemoveSongFromPlaylist function in databasefunctions.py
> Unittest - Testing the remove song function from the playlist

- templates/sharedplaylistpage.html
the shared playlistpage is the same as the playlistpage but users will have to enter a password before they can add songs. this page will be accessed for those who that particular playlist was shared to in the near future
> sharedplaylistpage added

- UserCreationTesting.py
- main.py
Testing if the user is added successfully to the database
Testing to make sure another user with the same email is not added.
> Mocked DB testing - if the User is Created

- databasefunctions.py
- main.py
- search.py
- static/playlistpage.css
- templates/playlistpage.html
- testingplaylistfunctions.py
Adding song to playlist now stores image URL in database and utilizes URL through jinja in playlistpage.html file 
Functionality:
> Song queue displays album covers

- static/landingpage.css
- static/playlistpage.css
- templates/landingpage.html
- templates/playlistpage.html
- templates/uponsigninfooter.html
Here is the updated playlist page. This took hours. Literally. Hours. I am talking 5+. Pls enjoy. 
I made other small edits along the way, such as the footer. There was a random large white space that wanted to be included in the footer. Fixed that. Can not remember all edits. 
This one was a long journey.
> Cleaned up the Playlist Page as well as a few other small edits.

- .dockerignore
- Procfile
- deployment.md
- fly.toml
- main.py
Deployed Version of the App with the deets.
> Deployment Deets

- main.py
- static/playlistpage.css
- templates/createPlaylistPage.html
- templates/homeheader.html
- templates/landheader.html
- templates/playlistpage.html
& more changes in the playlist page.
> Mostly header stuff, but some other changes to playlist page too.

- databasefunctions.py
- main.py
- static/SharedPlaylistMore.css
- static/userPlaylistpage.css
- templates/SharedPlaylistMore.html
- templates/UsersAndPlaylist.html
- templates/createPlaylistPage.html
- templates/playlistpage.html
- templates/userPlaylistpage.html
Combined PR
Users can now add descriptions to their playlist:
createPlaylistpage:
playlistpage:
Also, all playlists shared with user are now displayed on the userPlaylistpage.
Links go to the sharedplaylistpage.
Links go to the sharedplaylistpage.
Added another HTML to view all the shared playlists.
> Letting the user enter a playlist Description for their playlist +Shared Playlist Display

- main.py
- templates/UsersAndPlaylist.html
- templates/createPlaylistPage.html
- templates/playlistpage.html
- templates/sharedplaylistpage.html
I added genre to queries and added genre to the database. I also had certain functions in the sharedplaylist HTML correctly redirected search as the search function going back to the sharedplaylist page rather than the playlist page.
> genre and password and sharing works

- main.py
- templates/playlistpage.html
- templates/sharedplaylistpage.html
the adding function wasn't working because the selected genre was an unnecessary part being taken into the function. I created a model similar to the share model that asks if your sure you want to delete the specific song .
> fixed an adding issue and added model for delete confirmation

- main.py
- static/playlistpage.css
- templates/error.html
- templates/playlistpage.html
- templates/sharedplaylistpage.html
> error handling works. i tested it using the error route and i also made an invalid type with the playlist description.

- static/PlaylistMore.css
- static/createPlaylistPage.css
- static/playlistpage.css
- templates/PlaylistMore.html
- templates/SharedPlaylistMore.html
- templates/createPlaylistPage.html
- templates/playlistpage.html
- templates/sharedplaylistpage.html
- templates/userPlaylistpage.html
Now if there are over 4-5 playlists, it will maintain its size and not get all funky. 
Plus just a lot more stylistic changes in general.
> lots of style changes and adjustments made along the way.

- main.py
- templates/sharedplaylistpage.html
Added doc string for error and api calls retries 3 times with a interval of 5 secs
> Added doc string for error and api calls retries 3 times with a interval of 5

- main.py
- requirements.txt
- static/userPlaylistpage.css
- templates/NotificationDatabaseViewer.html
- templates/homeheader.html
- templates/notifications.html
- templates/sharedplaylistpage.html
Users receive notifications about songs being added or songs being removed from playlists associated with them.
Cases are taken into consideration:
1. Playlist owner adds/deletes a song --
owner and shared users notified
2. shared user adds/deletes a song --
owner and shared users notified
3. When a user searches a playlist and then adds/deletes a song --
the user gets added the to be notified list of the playlist and owner and shared users notified
Unread notifications will have a number beside the notification bell:
Notifications page:
Also, created a notification database for testing purposes:
(establishing a many to many relationship)
Also fixed the playlist description on shared playlist page.
> Notifications Feature Added to the App

- main.py
- templates/createPlaylistPage.html
- templates/sharedplaylistpage.html
changed the deleteforsharedusers to include a password. added password input in modal for sharedplaylist html. once password is correct, goes to regular playlistpage.
> Password for deleting as shared users

- static/playlistpage.css
- templates/playlistpage.html
- templates/sharedplaylistpage.html
> Fixing the playlistpage and the sharedplaylistpage.

- main.py
- templates/playlistpage.html
- templates/sharedplaylistpage.html
Iinitally when you open the playlist, its this default image:
Now only clicking the song image you show the song that's being played:
> Displaying image of the song playing
